<?php require './templates/header.phtml'; ?>
<div class="m-auto" style="width: 60rem;">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Edad</th>
            </tr>
        </thead>

        <?php foreach ($clients as $client) : ?>
            <tbody>
                <tr>
                    <th scope="row"><?= $client->id ?></th>
                    <td><?= $client->nombre ?></td>
                    <td><?= $client->apellido ?></td>
                    <td><?= $client->edad ?></td>
                <td><a href="clientes"><button class="btn btn-secondary">Volver</button> <a href="editClient/<?=$client->id?>"><button class="btn btn-warning">Modificar</button></td></a>
                </tr>
            <?php endforeach ?>
            </tbody>
    </table>
</div>
<?php require './templates/footer.phtml'; ?>