<?php if (isset($_SESSION['USER_ID'])) : ?>
    <div class="mt-5 w-25 mx-auto">
    <form method="POST" action="addClient">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="nombre" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Apellido</label>
            <input type="text" class="form-control" name="apellido">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Edad</label>
            <input type="number" class="form-control" name="edad">
        </div>
        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
</div>
<?php endif ?>