<?php require 'templates/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="validate"> 
        <div class="form-group">
            <label for="text">Username</label>
            <input type="text" class="form-control" id="username" name="username" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>

       <button type="submit">Entrar</button>
       
    </form>
</div>

<?php require 'templates/footer.phtml' ?>

