<?php if (isset($_SESSION['USER_ID'])) : ?>
    <div class="mt-5 w-25 mx-auto">
    <form method="POST" action="addTravel">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Destino</label>
            <input type="text" class="form-control" name="destino" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Precio</label>
            <input type="number" class="form-control" name="precio">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">ID Usuario</label>
            <input type="number" class="form-control" name="id_usuario">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Fecha Ida</label>
            <input type="text" class="form-control" name="fecha_ida">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Fecha Vuelta</label>
            <input type="text" class="form-control" name="fecha_vuelta">
        </div>
        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
</div>
<?php endif ?>