<?php require './templates/header.phtml'; ?>

<ul>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Destino</th>
                <th scope="col">Precio</th>
                <th scope="col">Fecha Ida</th>
                <th scope="col">Fecha Vuelta</th>
            </tr>
        </thead>
    </table>
    <?php foreach ($travels as $travel) : ?>
        <table class="table">
            <tbody class="table-group-divider">
                <tr>
                    <th scope="row"><?php echo $travel->id_viajes ?> </th>
                    <td><?php echo $travel->destino ?></td>
                    <td><?php echo $travel->precio ?></td>
                    <td><?php echo $travel->fecha_ida ?></td>
                    <td><?php echo $travel->fecha_vuelta ?></td>
                </tr>
            </tbody>

        </table>
    <?php endforeach ?>
</ul>

<?php require './templates/footer.phtml'; ?>