<?php require './templates/header.phtml'; ?>
<div class="m-auto" style="width: 60rem;">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Destino</th>
                <th scope="col">Usuario</th>
                <th scope="col">Precio</th>
                <th scope="col">Fecha Ida</th>
                <th scope="col">Fecha Vuelta</th>
            </tr>
        </thead>

        
            <tbody>
                <tr>
                    <th scope="row"><?= $travel->id_viajes ?></th>
                    <td><?= $travel->destino ?></td>
                    <td><?= $travel->id_usuario ?></td>
                    <td><?= $travel->precio ?></td>
                    <td><?= $travel->fecha_ida ?></td>
                <td><?= $travel->fecha_vuelta ?> <a href="viajes"><button class="btn btn-secondary">Volver</button> <a href="editTravel/<?=$travel->id_viajes?>"> <button class="btn btn-warning">Modificar</button></td></a> 
                </tr>
           
            </tbody>
    </table>
</div>
<?php require './templates/footer.phtml'; ?>